CC = g++
CXXFLAGS = -std=c++17
RM = rm
main: main.cpp
	@clear
	@$(CC) -o main main.cpp $(CXXFLAGS)
	@./main
	@$(RM) main

brut: brut.cpp
	@clear
	@$(CC) -o brut brut.cpp $(CXXFLAGS)
	@./brut
	@$(RM) brut